# SplatBin Configuration

[expiry]
# Maximum time a file can be uploaded for (in hours)
# -1 = infinity (no expiration limit)
# 168 = 1 week (default)
max_hours = 162

[upload]
# Maximum file size in MB
max_size_mb = 100

[server]
# Port to run on
port = 3000
# Server URL (used in examples and responses)
url = "https://your-domain.com"
