# splatbin config

[expiry]
# max upload lifetime (in hours)
# -1 = infinity (no expiration limit)
# 168 = 1 week (default)
max_hours = -1

# allow files to last for ever
allow_everlasting = true

[upload]
# max upload size in mb
max_size_mb = 100

[server]
port = 3000
url = "https://your-domain.com"
